jobs:
  - name: test-main
    plan:
    - get: lib
    - get: source
      trigger: true
    - task: rustfmt
      file: lib/tasks/rust/rustfmt.yml
    - task: clippy
      file: lib/tasks/rust/clippy.yml
    - task: run-tests
      file: lib/tasks/rust/test.yml
  - name: test-tag
    plan:
    - get: lib
    - get: tagged-commits
      trigger: true
    - task: rustfmt
      file: lib/tasks/rust/rustfmt.yml
      input_mapping: { source: tagged-commits }
    - task: clippy
      file: lib/tasks/rust/clippy.yml
      input_mapping: { source: tagged-commits }
    - task: run-tests
      file: lib/tasks/rust/test.yml
      input_mapping: { source: tagged-commits }
  - name: build-it
    plan:
    - get: lib
    - get: tagged-commits
      trigger: true
      passed: [ test-tag ]
    - in_parallel:
      - task: build-release-binary-linux
        file: lib/tasks/rust/build-release.yml
        input_mapping: { source: tagged-commits }
        params: { target: x86_64-unknown-linux-gnu }
        output_mapping: { binaries: x86_64-unknown-linux-gnu }
      # - task: build-release-binary-windows
      #   file: lib/tasks/rust/build-release.yml
      #   input_mapping: { source: tagged-commits }
      #   params: { target: x86_64-pc-windows-gnu }
      #   output_mapping: { binaries: x86_64-pc-windows-gnu }
      # - task: build-release-binary-darwin
      #   file: source/ci/lib/tasks/build-release.yml
      #   input_mapping: { source: tagged-commits }
      #   params:
      #     target: x86_64-apple-darwin
      #     MACOSX_DEPLOYMENT_TARGET: 10.7
      #   output_mapping: { binaries: x86_64-apple-darwin }
    - in_parallel:
      - task: compress-release-binary-linux
        file: lib/tasks/rust/compress.yml
        params:
          target: x86_64-unknown-linux-gnu
          prefix: rustomato
        input_mapping: { binaries: x86_64-unknown-linux-gnu }
        output_mapping: { compressed: assets-linux }
# Error: tar: *: No such file or directory
# https://ci.uhlig.it/teams/main/pipelines/rustomato/jobs/build-it/builds/15#L61fabd58:8
      # - task: compress-release-binary-windows
      #   file: lib/tasks/rust/compress.yml
      #   params:
      #     target: x86_64-pc-windows-gnu
      #     prefix: rustomato
      #   input_mapping: { binaries: x86_64-pc-windows-gnu }
      #   output_mapping: { compressed: assets-windows }
      # - task: compress-release-binary-darwin
      #   file: source/ci/lib/tasks/compress.yml
      #   input_mapping: { binaries: x86_64-apple-darwin }
      #   params:
      #     target:
      #     MACOSX_DEPLOYMENT_TARGET: 10.7
      #   output_mapping: { compressed: assets-darwin }
    - task: collect-assets
      file: lib/tasks/rust/collect.yml
      input_mapping:
        linux: assets-linux
        windows: assets-linux
        darwin: assets-linux # TODO workaround until we have Darwin working
      output_mapping: { collected: assets }
    - task: compile-release-notes
      file: lib/tasks/git/release-notes.yml
      input_mapping: { repo: tagged-commits }
      output_mapping: { release-notes: release-notes }
    - put: gh-release
      params:
        name: tagged-commits/.git/ref
        body: release-notes/commits-since-last-tag.txt
        tag: tagged-commits/.git/ref
        globs:
          - assets/*
    on_success:
        do:
          - task: create-publication-message
            file: lib/tasks/git/create-release-message.yml
            input_mapping: { source: tagged-commits }
            params: { project_name: rustomato }
            output_mapping: { message: telegram-message }
          - put: telegram-notification
            params:
              chat_id: ((telegram.chat_id))
              text_file: telegram-message/new-release.txt
resources:
  - name: lib
    type: git
    icon: github-circle
    source: &github
      uri: git@github.com:suhlig/concourse-task-library.git
      private_key: ((github.ssh_key))
  - name: source
    type: git
    icon: github
    source: &source
       uri: git@github.com:suhlig/rustomato.git
       private_key: ((github.ssh_key))
  - name: tagged-commits
    type: git
    icon: tag
    source:
      <<: *source
      fetch_tags: true
      tag_filter: v*
  - name: gh-release
    type: github-release
    icon: github-circle
    source:
      owner: suhlig
      repository: rustomato
      access_token: ((github.token))
      pre_release: true
      drafts: true
  - name: telegram-notification
    type: telegram-notification
    icon: telegram
    source:
      bot_token: ((telegram.bot_token))
resource_types:
  - name: telegram-notification
    type: docker-image
    source:
      repository: w32blaster/concourse-telegram-notifier
