#!/usr/bin/env zsh

set -euo pipefail

CONCOURSE_TARGET=soda
PIPELINE_NAME=rustomato
srcdir=${0:a:h}

fly \
    --target "$CONCOURSE_TARGET" \
  set-pipeline \
    --pipeline="$PIPELINE_NAME" \
    --config "$srcdir"/pipelines/release.yml \
    --load-vars-from="$srcdir/private-config.yml"
